name: CI Pipeline

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: docker build -t flask-devops-demo .

    - name: Run container (basic test)
      run: |
        docker run -d -p 5000:5000 flask-devops-demo
        sleep 10
        curl --retry 5 --retry-connrefused http://localhost:5000
